apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: devops-task-manager 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: devops-task-manager 
  template: 
    metadata: 
      labels: 
        app: devops-task-manager
    spec: 
      containers: 
      - name: task-manager
        image: uzairchini/devops-task-manager:b96748a9a5245abad9b330d27c929892fc01a7fd
        ports: 
        - containerPort: 5000
        readinessProbe: 
          httpGet: 
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe: 
          httpGet: 
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
          