name: Docker Build and Push 
on: 
 push: 
  branches: 
    - main
permissions:
  contents: write 
jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          persist-credentials: true
      - name: Configure Git 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t uzairchini/devops-task-manager:${{ github.sha }} -t uzairchini/devops-task-manager:latest .
      - name: Push SHA Tag 
        run: docker push uzairchini/devops-task-manager:${{ github.sha }}
      
      - name: Push Latest Tag
        run: docker push uzairchini/devops-task-manager:latest 
      
      - name: Update Kubernetes Deployment 
        run: |
          sed -i "s|image: uzairchini/devops-task-manager:.*|image: uzairchini/devops-task-manager:${{ github.sha }}|" k8s/deployment.yaml
      - name: Commit Deployment Update
        run: |
          git add k8s/deployment.yaml
          git diff --cached --quiet || git commit -m "Update deployment image to ${{ github.sha }} [skip ci]"

      - name: Push Deployment Update 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main